--function ui:triangle(id)
--  return function(data)
--    local tr = Triangle.new(id)
--    for k, v in pairs(data) do
--      if k == "point1" then
--        tr:setPoint1(v)
--      elseif k == "point2" then
--        tr:setPoint2(v)
--      elseif k == "point3" then
--        tr:setPoint3(v)
--      elseif k == "color1" then
--        tr:setColor1(v)
--      elseif k == "color2" then
--        tr:setColor2(v)
--      elseif k == "color3" then
--        tr:setColor3(v)
--      elseif k == "color" then
--        tr:setColor(v)
--      end
--    end
--    return tr
--  end
--end
